import type { Metadata } from "next";
import { Playfair_Display } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Server-side-codes/NavbarServer/Navbar";
import Footer from "@/components/Server-side-codes/Footer/Footer";
import Providers from "./Redux/Provider/provider"; // <- default import here

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { Toaster } from "react-hot-toast";

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Mango Chairs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${playfairDisplay.variable} antialiased`}>
        <Providers>
          <Navbar
            headerEndpoint="frontend/headers/"
            categoryEndpoint="frontend/categories/"
          />
          {children}
          <Toaster
            position="top-center"
            toastOptions={{
              className:
                "bg-black text-white px-4 py-2 rounded-md shadow-md text-sm",
              duration: 2000,
            }}
          />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
